#!/usr/bin/env bash
set -euo pipefail

MAJOR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${1:-$(pwd)}"
INTERNAL="$MAJOR_ROOT/skills/internal"
AGENT_SKILLS="$TARGET/.agents/skills"
CLAUDE_SKILLS="$TARGET/.claude/skills"
CODEX_SKILLS="$TARGET/.codex/skills"
LOCK="$TARGET/MAJOR_SKILLS.lock"
TMP="${TMPDIR:-/tmp}/major-skills-$$"

mkdir -p "$AGENT_SKILLS" "$CLAUDE_SKILLS" "$CODEX_SKILLS" "$TMP"

copy_skill_dir() {
  local src="$1"
  local name
  name="$(basename "$src")"
  rm -rf "$AGENT_SKILLS/$name" "$CLAUDE_SKILLS/$name" "$CODEX_SKILLS/$name"
  cp -R "$src" "$AGENT_SKILLS/$name"
  cp -R "$src" "$CLAUDE_SKILLS/$name"
  cp -R "$src" "$CODEX_SKILLS/$name"
}

for dir in "$INTERNAL"/*; do
  [ -d "$dir" ] && copy_skill_dir "$dir"
done

clone_repo() {
  git clone --depth 1 "https://github.com/$1.git" "$2"
}

copy_named() {
  local root="$1" name="$2" found
  found="$(find "$root" -type f -name SKILL.md -path "*/$name/SKILL.md" -print -quit || true)"
  if [ -z "$found" ]; then
    echo "ERROR: required external skill missing upstream: $name" >&2
    return 1
  fi
  copy_skill_dir "$(dirname "$found")"
}

EMIL="$TMP/emil"
ANTHROPIC="$TMP/anthropic"
OPENAI="$TMP/openai"
GRAPH="$TMP/graph"

clone_repo emilkowalski/skills "$EMIL"
clone_repo anthropics/skills "$ANTHROPIC"
clone_repo openai/skills "$OPENAI"
clone_repo codejunkie99/graph-engineering "$GRAPH"

# Emil: install the complete current bundle so new Emil skills are picked up automatically.
while IFS= read -r skill; do
  copy_skill_dir "$(dirname "$skill")"
done < <(find "$EMIL" -type f -name SKILL.md)

for skill in \
  frontend-design \
  webapp-testing \
  mcp-builder \
  skill-creator \
  algorithmic-art; do
  copy_named "$ANTHROPIC" "$skill"
done

for skill in \
  playwright \
  vercel-deploy \
  figma-use \
  figma-implement-design \
  figma-generate-design \
  security-threat-model \
  pdf; do
  copy_named "$OPENAI" "$skill"
done

copy_named "$GRAPH" graph-engineering

# Validate that every Major internal skill has a SKILL.md and every selected external
# skill actually arrived. The installer must fail rather than claiming a partial bundle.
missing=0
for dir in "$INTERNAL"/*; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  if [ ! -f "$AGENT_SKILLS/$name/SKILL.md" ]; then
    echo "ERROR: missing installed internal skill: $name" >&2
    missing=1
  fi
done

for name in \
  animate animation-vocabulary apple-design emil-design-eng find-animation-opportunities \
  improve-animations pick-ui-library prototype review-animations \
  frontend-design webapp-testing mcp-builder skill-creator algorithmic-art \
  playwright vercel-deploy figma-use figma-implement-design figma-generate-design \
  security-threat-model pdf graph-engineering; do
  if [ ! -f "$AGENT_SKILLS/$name/SKILL.md" ]; then
    echo "ERROR: missing installed recurring skill: $name" >&2
    missing=1
  fi
done

if [ "$missing" -ne 0 ]; then
  echo "Major skill installation incomplete; refusing success." >&2
  exit 1
fi

{
  echo "# Generated by Major skill installer"
  echo "installed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "major_repo=$MAJOR_ROOT"
  for repo in "$EMIL" "$ANTHROPIC" "$OPENAI" "$GRAPH"; do
    echo "source=$(git -C "$repo" remote get-url origin) commit=$(git -C "$repo" rev-parse HEAD)"
  done
  echo "[skills]"
  find "$AGENT_SKILLS" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort
} > "$LOCK"

rm -rf "$TMP"

echo "Major skills installed and validated into $TARGET"
echo "Registry: $LOCK"
