#!/usr/bin/env bash
set -euo pipefail

MAJOR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${1:-$(pwd)}"
INTERNAL="$MAJOR_ROOT/skills/internal"
AGENT_SKILLS="$TARGET/.agents/skills"
CLAUDE_SKILLS="$TARGET/.claude/skills"
CODEX_SKILLS="$TARGET/.codex/skills"
LOCK="$TARGET/MAJOR_SKILLS.lock"
TMP="${TMPDIR:-/tmp}/major-skills-$$"

mkdir -p "$AGENT_SKILLS" "$CLAUDE_SKILLS" "$CODEX_SKILLS" "$TMP"

copy_skill_dir() {
  local src="$1"; local name="$(basename "$src")"
  rm -rf "$AGENT_SKILLS/$name" "$CLAUDE_SKILLS/$name" "$CODEX_SKILLS/$name"
  cp -R "$src" "$AGENT_SKILLS/$name"
  cp -R "$src" "$CLAUDE_SKILLS/$name"
  cp -R "$src" "$CODEX_SKILLS/$name"
}

for dir in "$INTERNAL"/*; do [ -d "$dir" ] && copy_skill_dir "$dir"; done

clone_repo() { git clone --depth 1 "https://github.com/$1.git" "$2"; }
copy_named() {
  local root="$1" name="$2" found
  found="$(find "$root" -type f -name SKILL.md -path "*/$name/SKILL.md" -print -quit || true)"
  [ -n "$found" ] && copy_skill_dir "$(dirname "$found")" || echo "WARN missing external skill: $name"
}

EMIL="$TMP/emil"; ANTHROPIC="$TMP/anthropic"; OPENAI="$TMP/openai"; GRAPH="$TMP/graph"
clone_repo emilkowalski/skills "$EMIL" || true
clone_repo anthropics/skills "$ANTHROPIC" || true
clone_repo openai/skills "$OPENAI" || true
clone_repo codejunkie99/graph-engineering "$GRAPH" || true

# Emil: entire current bundle, by design.
if [ -d "$EMIL" ]; then
  while IFS= read -r skill; do copy_skill_dir "$(dirname "$skill")"; done < <(find "$EMIL" -type f -name SKILL.md)
fi
[ -d "$ANTHROPIC" ] && { copy_named "$ANTHROPIC" frontend-design; copy_named "$ANTHROPIC" webapp-testing; }
[ -d "$OPENAI" ] && { copy_named "$OPENAI" security-threat-model; copy_named "$OPENAI" pdf; }
[ -d "$GRAPH" ] && copy_named "$GRAPH" graph-engineering

{
  echo "# Generated by Major skill installer"
  echo "installed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "major_repo=$MAJOR_ROOT"
  for repo in "$EMIL" "$ANTHROPIC" "$OPENAI" "$GRAPH"; do
    if [ -d "$repo/.git" ]; then echo "source=$(git -C "$repo" remote get-url origin) commit=$(git -C "$repo" rev-parse HEAD)"; fi
  done
  echo "[skills]"
  find "$AGENT_SKILLS" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort
} > "$LOCK"

rm -rf "$TMP"
echo "Major skills installed into $TARGET"
echo "Registry: $LOCK"
